import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Download, History, Share2, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { formatBytes, formatDate } from '@/lib/utils';
export function DocumentCard({ document, onShare, onDownload, onDelete, onViewVersions, }) {
    return (_jsxs(Card, { className: "p-5", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-lg font-semibold text-ink", children: document.name }), _jsx("p", { className: "mt-1 text-sm text-slate-500", children: document.folder?.path ?? 'Root' })] }), _jsxs(Badge, { children: ["v", document.version] })] }), _jsxs("div", { className: "mt-4 grid grid-cols-2 gap-3 text-sm text-slate-500", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.18em] text-slate-400", children: "Size" }), _jsx("p", { className: "mt-1 font-semibold text-ink", children: formatBytes(Number(document.size)) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.18em] text-slate-400", children: "Updated" }), _jsx("p", { className: "mt-1 font-semibold text-ink", children: formatDate(document.updatedAt) })] })] }), document.tags.length ? (_jsx("div", { className: "mt-4 flex flex-wrap gap-2", children: document.tags.map((tag) => (_jsxs("span", { className: "rounded-full bg-sand px-3 py-1 text-xs font-semibold text-slate-600", children: ["#", tag] }, tag))) })) : null, _jsxs("div", { className: "mt-5 flex flex-wrap gap-2", children: [_jsxs(Button, { variant: "ghost", onClick: () => onDownload(document), children: [_jsx(Download, { className: "mr-2 h-4 w-4" }), "Download"] }), _jsxs(Button, { variant: "ghost", onClick: () => onShare(document), children: [_jsx(Share2, { className: "mr-2 h-4 w-4" }), "Share"] }), _jsxs(Button, { variant: "ghost", onClick: () => onViewVersions(document), children: [_jsx(History, { className: "mr-2 h-4 w-4" }), "Versions"] }), _jsxs(Button, { variant: "danger", onClick: () => onDelete(document), children: [_jsx(Trash2, { className: "mr-2 h-4 w-4" }), "Delete"] })] })] }));
}
